force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Weather Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weathers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather__c/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Humidity__c.field-meta.xml
<CustomField>
    <fullName>Humidity__c</fullName>
    <label>Humidity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Pressure__c.field-meta.xml
<CustomField>
    <fullName>Pressure__c</fullName>
    <label>Pressure</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Temp_Feels_Like__c.field-meta.xml
<CustomField>
    <fullName>Temp_Feels_Like__c</fullName>
    <label>Temp Feels Like</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Wind_Speed__c.field-meta.xml
<CustomField>
    <fullName>Wind_Speed__c</fullName>
    <label>Wind Speed</label>
    <precision>17</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather_Setting__c/Weather_Setting__c.object-meta.xml
<CustomObject>
    <label>Weather Setting</label>
    <nameField>
        <label>Weather Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather_Setting__c/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Weather_Setting__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>de</fullName>
            </value>
            <value>
                <fullName>en</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>it</fullName>
            </value>
            <value>
                <fullName>ja</fullName>
            </value>
            <value>
                <fullName>pl</fullName>
            </value>
            <value>
                <fullName>ua</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WeatherAPIService.cls
public with sharing class WeatherAPIService {
    @AuraEnabled
    public static List<String> getLocations(){
        List<Weather_Setting__c> settings = getSettings();

        List<String> cities = new List<String>();
        for(Weather_Setting__c setting : settings){
            cities.add(setting.City_Name__c);
        }
        
        return cities;
    }
    public static List<Weather_Setting__c> getSettings(){
        List<Weather_Setting__c> settings = [
            SELECT City_Name__c, Language__c
            FROM Weather_Setting__c
        ];

        return settings; 
    }
    public static List<WeatherWrapper> getWeathers(List<Weather_Setting__c> settings){
        List<WeatherWrapper> results = new List<WeatherWrapper>();
        Get_Weather_Setting__mdt mdt = Get_Weather_Setting__mdt.getInstance('My_Api');
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        String url;
        HTTPResponse response;

        for(Weather_Setting__c setting : settings){
            url = mdt.Endpoint__c + setting.City_Name__c + '&appid=' + mdt.Api_Id__c + setting.Language__c;
            req.setEndpoint(url);
            response = http.send(req);
            results.add((WeatherWrapper) System.JSON.deserialize(response.getBody(), WeatherWrapper.class));
        }
        return results;
    }
    public static void createWeathers(List<WeatherWrapper> results){
        List<Weather__c> weathers = new List<Weather__c>();
        for(WeatherWrapper result : results){
            Weather__c weather = new Weather__c(
                City_Name__c = result.name,
                Date__c = System.today(),
                Humidity__c = result.Main.humidity,
                Latitude__c = result.Coord.lat,
                Longitude__c = result.Coord.lon,
                Pressure__c = result.Main.pressure,
                Temp_Feels_Like__c = result.Main.feels_like,
                Temperature__c = result.Main.temp,
                Wind_Speed__c = result.Wind.speed
            );
            weathers.add(weather);
        }
        

        insert weathers;
    }
}