force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Weather Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weathers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather__c/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Humidity__c.field-meta.xml
<CustomField>
    <fullName>Humidity__c</fullName>
    <label>Humidity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Pressure__c.field-meta.xml
<CustomField>
    <fullName>Pressure__c</fullName>
    <label>Pressure</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Temp_Feels_Like__c.field-meta.xml
<CustomField>
    <fullName>Temp_Feels_Like__c</fullName>
    <label>Temp Feels Like</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Weather_Description__c.field-meta.xml
<CustomField>
    <fullName>Weather_Description__c</fullName>
    <label>Weather Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Wind_Speed__c.field-meta.xml
<CustomField>
    <fullName>Wind_Speed__c</fullName>
    <label>Wind Speed</label>
    <precision>17</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GetWeatherResponse.cls
public with sharing class GetWeatherResponse {
    @AuraEnabled
    public static void getWeather(){
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        String geoUrl = 'https://api.openweathermap.org/geo/1.0/direct?q=Lviv&limit=1&appid=07e676cc2e56bb333fef2dc4a8dc1738';
        req.setEndpoint(geoUrl);
        req.setMethod('GET');
        HttpResponse response = http.send(req);

        if(response.getStatusCode() == 200){
            List<Object> results=(List<Object>)JSON.deserializeUntyped(response.getBody());

            System.debug(results);
        }
        else {
            System.debug('bruh');
        }

        String url = 'https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid=';
    }
    @AuraEnabled
    public static List<Weather__c> getAllWeatherRecords(){
        List<Weather__c> weathers = [
            SELECT City_Name__c, Date__c, Humidity__c, Latitude__c, Longitude__c, Pressure__c, Temp_Feels_Like__c, Temperature__c, Weather_Description__c, Wind_Speed__c
            FROM Weather__c
        ];

        return weathers;
    }
}