force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Weather Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weathers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather__c/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weather_Setting__c/Weather_Setting__c.object-meta.xml
<CustomObject>
    <label>Weather Setting</label>
    <nameField>
        <label>Weather Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather_Setting__c/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/WeatherControllerTest.cls
@isTest
private with sharing class WeatherControllerTest {
    @TestSetup
    private static void makeData(){
        TestDataFactory.createWeathers(1, 'TestCity');

        TestDataFactory.createWeatherSettings(1, 'Osaka');
    }

    @isTest
    private static void getCityWeatherRecordsTest(){
        Test.startTest();
        List<Weather__c> weathers = WeatherController.getCityWeatherRecords('TestCity');
        Test.stopTest();

        System.assertEquals(1, weathers.size());
        System.assertEquals('TestCity', weathers[0].City_Name__c);
    }

    @isTest
    private static void getSettingsTest(){
        Test.startTest();

        List<Weather_Setting__c> weatherSettings = WeatherController.getSettings();

        System.assertEquals(1, weatherSettings.size());
        System.assertEquals('Osaka', weatherSettings[0].City_Name__c);

        Test.stopTest();
    }
}